---

- hosts: all
  become: true
  tasks: 

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
      

  - name: install apache and php
    apt: 
      name: 
        - "{{apache_package}}"
        - "{{php_package}}"
    when: ansible_distribution in ["Ubuntu, Debian"]
